### ISSUE TITLE
Project Description

### ISSUE THREAD

**Issue by anttim1** [pratt-savi-810/project-anttim1#2]
Arc has topography tools but once overlapping polygons and gaps have been found, topology errors need to be resolved manually -- a daunting task when there are 20,000 errors, which sometimes happens.

I will write a code that automatically resolves errors by adding error polygons created by topology tools to the neighboring polygon of the original feature class with which the error polygon has the longest common boundary.

**Comment by nygeog** [comment]
@anttim1 please start;

1. Investigating which arcpy code you can use for this (make a list and link out to some of the toolbox tools you might be able to use for this)

2. Writing out some pseudocode or an outline of the steps that you will need your code to perform.

**Comment by anttim1** [comment]
I will use [Topology tools](http://desktop.arcgis.com/en/arcmap/10.3/tools/data-management-toolbox/create-topology.htm) and the [Polygon Neighbors tool] (http://pro.arcgis.com/en/pro-app/tool-reference/analysis/polygon-neighbors.htm).

The code creates a topology for a shapefile and creates a polygon feature class from topology errors. It then merges the error feature class with the original shapefile and finds the length of neighboring polygons of the gap polygons. The code then gives an identifying value from a field in the original shapefile to the error polygon using the length of the common boundary as criteria (picking the value from the neighbor with the longest common boundary.

**Comment by nygeog** [comment]
Complete.
