### ISSUE TITLE
Project Code

### ISSUE THREAD

**Issue by anttim1** [pratt-savi-810/project-anttim1#3]
import os
import arcpy
import pandas as pd
# specify shapefile path and field that the topology is built on
shapefile = "C:/Temp/Topology/Ecological_communities.shp"
field = "TYPE"
# create variables for necessary paths, create gdb, import shapefile into feature dataset
gdb = os.path.basename(shapefile[:-3] + 'gdb')
gdbDir= os.path.dirname(shapefile)
arcpy.CreateFileGDB_management(gdbDir, gdb)
arcpy.env.workspace = gdbDir + '/' + gdb
feature_ds = arcpy.env.workspace + '/topology_ds'
data = arcpy.env.workspace + '/topology_ds/' + os.path.basename(shapefile[:-4])
topology = feature_ds + '/Topology'
arcpy.CreateFeatureDataset_management(arcpy.env.workspace, "topology_ds", shapefile[:-3] + 'prj')
arcpy.FeatureClassToGeodatabase_conversion([shapefile], "topology_ds")
# Create topology, add feature class, define rules
arcpy.CreateTopology_management(feature_ds, "Topology")
arcpy.AddFeatureClassToTopology_management(topology, data)
arcpy.AddRuleToTopology_management(topology, "Must Not Have Gaps (Area)",data,"","","")
arcpy.ValidateTopology_management(topology)
# create polygon shapefile from errors and merge with original data
arcpy.ExportTopologyErrors_management(topology, "", "gapErrors")
arcpy.FeatureToPolygon_management("gapErrors_line","topo_errors_gaps")
arcpy.SelectLayerByAttribute_management ("topo_errors_gaps", "NEW_SELECTION", '"Shape_Area" < 10000')
arcpy.AddField_management("topo_errors_gaps", field, "STRING")
g = "g"
arcpy.CalculateField_management('topo_errors_gaps',field,g)
arcpy.SelectLayerByAttribute_management ("topo_errors_gaps", "SWITCH_SELECTION")
arcpy.DeleteRows_management("topo_errors_gaps")
arcpy.Merge_management(["topo_errors_gaps",shapefile],"topomerged")
# Get neighbor table and export to gdb
arcpy.PolygonNeighbors_analysis('topomerged', 'topo_gaps',['OBJECTID', field])
arcpy.TableToGeodatabase_conversion('topo_gaps',arcpy.env.workspace)
#table to array and array to dataframe
nbr_field = ‘nbr_’ + field
arr = arcpy.da.FeatureClassToNumPyArray(("topo_gaps"), ("src_OBJECTID", nbr_field, "LENGTH"))
index = [str(i) for i in range(1, len(arr)+1)]
df = pd.DataFrame(arr, index=index)
# to numeric?
# df[['src_OBJECTID','LENGTH']] = df[['src_OBJECTID','LENGTH']].apply(pd.to_numeric)
#select rows from df and export to csv and to gdb
idx = df.groupby(['src_OBJECTID'])['LENGTH'].transform(max) == df['LENGTH']
df_select = df [idx]
df_select.to_csv(gdbDir+'/joinme.csv', index=False)
arcpy.TableToTable_conversion(gdbDir+'/joinme.csv', arcpy.env.workspace, "joinme")

# Join field -- got stuck here, table would join manually but not with arcpy
arcpy.JoinField_management('topo_errors_gaps', 'OBJECTID', 'joinme', 'src_OBJECTID', 'nbr_TYPE')

**Comment by nygeog** [comment]
@anttim1 could you upload or paste your code to GitHub as a .py file in the main folder: https://github.com/pratt-savi-810/project-anttim1

Please upload your working code to GitHub - this video is helpful for GitHub desktop.  https://resources.github.com/webcasts/GitHub-and-GitHub-desktop/
