### ISSUE TITLE
Error "unorderable types: str() < float()"

### ISSUE THREAD

**Issue by anttim1** [pratt-savi-810/project-anttim1#4]
When I try to set a threshold variable for polygons that are included in the error polygons I get the error "unorderable types: str() < float()". I've tried changing the data type of the "threshold" variable, but no help. The code currently has the threshold set on line 30 and it works this way.

**Comment by nygeog** [comment]
@anttim1 Sorry, in the right hand column, you can Assign someone, that way I'd get an email alert. 

I've been waiting on a project submission to start all the reviews, but I'll go ahead with yours now. 

I'm reviewing the code right now.

**Comment by nygeog** [comment]
I just assigned myself to this Issue.

**Comment by nygeog** [comment]
@anttim1 is it still on line 30 - I'm a bit confused by what you are trying to apply. You want to use the `threshold` variable somewhere, which line (is it 30?).

**Comment by anttim1** [comment]
Sorry, that was definitely not clear.

I Would like to do "Shape_Area" < threshold in the selection. I get the
error when I try to use the "threshold" variable instead of the number
10000.

**Comment by nygeog** [comment]
Unf. with some arcpy definition queries, you have to sometimes do some counterintuitive stuff, like casting values that are numbers (and should be numbers) into strings. Have you tried something like: 

`'"Shape_Area" < ' + str(threshold)`

You may even need to try a few other things, I'm not sure if you need `!Shape_Area!` and sometimes you'll need to add on something like ` + ' " ' ` or ` + " ' "  ` close off some arcpy expressions.

**Comment by nygeog** [comment]
@anttim1 did that work? Let me know when you have a chance. Thanks. If not I'll take a more thorough look.

**Comment by anttim1** [comment]
Got really busy at work and didn't have time to check this earlier. None of that seems to work. Good news is I probably figured out why the code didn't run for you: you need to add a map to the document for it to run.

**Comment by nygeog** [comment]
It worked for me in ArcGIS Pro.

**Comment by nygeog** [comment]
You're all good. It worked. I may do a few things to wrap your code in a
function tonight, but consider your project submitted and complete.

**Comment by nygeog** [comment]
I'll take a look and hopefully fix whatever is going on with that distance
parameter.

**Comment by nygeog** [comment]
Seems to be working now here: https://github.com/pratt-savi-810/project-anttim1/blob/master/topology_repair.py#L30
